# Generated by Django 4.0.6 on 2022-07-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userslug', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
